# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://app.tankery.me
baseurl: /pace
title: Pace
email: tankery.chen@gmail.com
author: Tankery Chen
description: Pace is a music player for runners, that only plays the music matching your pace.
credits: |
  Credits:<br/>
  Made by <a href="https://github.com/swcool/landing-page-theme">Landing Page Jekyll theme</a>.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: 
